### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Library libmy.so not found when dynamically loading library with native code

### ISSUE THREAD

**Issue by geaden** [lukeFalsina/Grab-n-Run#2]
Hi. First of all, thanks for a great library to securely load classes. 

When trying to implement provided in README example, I decided to use native code in my loadable library. But I didn't find a way to specify the correct path to the native library (since factory method createDexClassLoader in SecureLoaderFactory takes library path as the second argument). Should I download library separately (I used stored in Dropbox implementation)? How to do it properly (since FileDownloader is protected, it is not accessible from my code) and where to store this library?

Thanks.

**Comment by lukeFalsina** [comment]
That's a good point indeed.

At the moment the full retrieve and integrity verification is implemented only for libraries containing dex files (the first parameter of createDexClassLoader in SecureLoaderFactory), and not for the native libraries (the second parameter). The path pointing to native libraries is simply carried over to the native DexClassLoader. You can see this here:

https://github.com/lukeFalsina/Grab-n-Run/blob/RefactoringAndFurtherTesting/gnr/app/src/main/java/it/necst/grabnrun/SecureLoaderFactory.java#L286

I could make the FileDownloader public but this would not really solve the problem since you would still need to manually handle the storage and the integrity verification of the native libraries.

So probably it's better instead to directly implement this feature in GNR. This may require a significant refactoring since I would like to reuse most of the logic that I have already implemented for the dex libraries. I can start working on it from next week. Would this be OK with you? :)

**Comment by geaden** [comment]
Yes, sure, this would be great! Thanks.

**Comment by lukeFalsina** [comment]
Hi again Gennady.

Can you please paste here a sample snippet of code to make me better understand your use case.
I'm asking this because I have actually never implemented a dynamic code loading feature using native code, and I think an exemplifying snippet will greatly help me to clarify the requirements for your use case.

**Comment by geaden** [comment]
@lukeFalsina Hello, Luke! Sorry for a long delay. Unfortunately, I missed your last comment.

Regarding the native library. I used [this project](https://github.com/Fi5t/NDK-Demo)  as a dynamically loaded library with native code. I had an interface with two methods `encrypt` and `decrypt` that is used in both dynamic library and my application. After requesting the apk with native code and calling decrypt method, just like in the examples, I got `java.lang.UnsatisfiedLinkError: Library libsecurity.so not found`. In order to make it work, I had to put compiled `libsecurity.so` along with apk and download it also. After that I could pass native library path and exception is gone. But, in order to make it, I had to duplicate code from the FileDownloader to be able to download native library. Please, let me know, if full project code is needed (with main application, interface class and slightly changed original NDK-Demo project).

Thanks.

**Comment by lukeFalsina** [comment]
Hey @geaden, if you could indeed share the full project code as you suggested it would be really useful because then I can write some test cases representing your request and patch Grab'n Run to support it.
Hope to hear from you soon :)

**Comment by lukeFalsina** [comment]
No followup on this one.
